### ISSUE TITLE
Decklists

### ISSUE THREAD

**Issue by Acvmf** [manoa-the-gathering/ManoaTheGathering#2]
1. Make a list of all cards we're going to use
2. Each card will have its new name and description of picture
3. Split up the cards based on which deck its a part of

Estimated time: a few hours max

**Comment by Acvmf** [comment]
[spells.txt](https://github.com/manoa-the-gathering/ManoaTheGathering/files/565376/spells.txt)
Here's a list of the cards in all of the lists John put in slack, duplicates removed.

**Comment by JHeadland** [comment]
I made a text file with the decklists for Naya Burn and Affinity (since Burn/Jund has a 70/30 winrate), it's not done yet as I'm putting what we'll rename the cards to on it. The file is uploaded as "decklists.txt" in the doc folder on the MTG repo.

Also, we could just split this issue up into 2 parts rather than 3, one for each deck (since affinity is mostly colorless, but also has red and black).

**Comment by JHeadland** [comment]
[decklists.txt](https://github.com/manoa-the-gathering/ManoaTheGathering/files/565991/decklists.txt)
